In [2]:
import tensorflow as tf

# Check version
print(tf.__version__)
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

2.20.0


In [6]:
x = tf.constant(4, shape=(1, 1), dtype=tf.float32)
print(x)


tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [3]:
# From Python list
tensor_1d = tf.constant([1, 2, 3, 4])
tensor_2d = tf.constant([[1, 2], [3, 4]])
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [5]:
print(tensor_3d)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [10]:
x= tf.constant(4, shape=(1, 1), dtype=tf.float32)
y= tf.constant([[1, 2, 3], [4, 5, 6]], shape=(3, 2))

In [11]:
print(x)
print(y)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


# Variables

In [23]:
# Variables can be updated
v = tf.Variable([1.0, 2.0, 3.0])
v.assign_add([1, 1, 1]) 
print(*v.numpy())

2.0 3.0 4.0


# Special

In [12]:
eye = tf.eye(3)  
ones = tf.ones((4, 3))  
zeros = tf.zeros((3, 2, 5))  

In [17]:
print(eye)
print(60*"*")
print(ones)
print(60*"*")
print(zeros)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
************************************************************
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(4, 3), dtype=float32)
************************************************************
tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 2, 5), dtype=float32)


# Arithematic

In [24]:
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])


In [26]:
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x ** 2)


tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)
tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)
tf.Tensor([1 4 9], shape=(3,), dtype=int32)


# Random tensors

In [18]:
random_normal = tf.random.normal((3, 3), mean=0, stddev=1)

random_int = tf.random.uniform((2, 2), minval=0, maxval=10, dtype=tf.int32)

In [19]:
print(random_normal)

tf.Tensor(
[[-0.6680875   0.71867836 -0.37126034]
 [-0.25629243  1.6226988  -0.14418295]
 [-0.26953214  0.7371778  -0.21532565]], shape=(3, 3), dtype=float32)


In [20]:
print(random_int)

tf.Tensor(
[[8 4]
 [2 5]], shape=(2, 2), dtype=int32)


# Range

In [27]:
x = tf.range(9)
x = tf.reshape(x, (3, 3))


In [28]:
print(x)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


# Transpose

In [30]:
tf.transpose(x, perm=[1, 0])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]], dtype=int32)>

# Automatic Differentiation

## partial differential with respect to xand with respect to y

In [80]:
x = tf.Variable(3.0)
y = tf.Variable(4.0)

with tf.GradientTape() as tape:
    z = x**2 + y**3

grads = tape.gradient(z, [x, y])


In [81]:
grads

[<tf.Tensor: shape=(), dtype=float32, numpy=6.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=48.0>]

# Simple neural network

In [82]:
import numpy as np
import tensorflow as tf

x_train = np.array([[1], [2], [3], [4], [5]], dtype=np.float32)
y_train = np.array([[3], [5], [7], [9], [11]], dtype=np.float32)


#### Sequential API is a Keras model type that builds a neural network as a linear stack of layers, 
#### where each layer has exactly 

#### one input and one output,

In [75]:
model = tf.keras.Sequential([
    tf.keras.Input(shape=(1,)),
    tf.keras.layers.Dense(64, activation="relu"),
    tf.keras.layers.Dense(1)
])


In [76]:
# model.compile(
#     optimizer="adam",
#     loss="mse",
#     metrics=["mae"]
# )
model.compile(
    optimizer=tf.keras.optimizers.SGD(learning_rate=0.01),
    loss="mse"
)


In [77]:
model.fit(x_train, y_train, epochs=10)


Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 183ms/step - loss: 68.5357
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 11.6058
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.8361
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.0381
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.0372
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 0.0364
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.0356
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0348
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.0340
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.0333


In [78]:
model.predict(np.array([[6]], dtype=np.float32))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step


array([[13.275963]], dtype=float32)

# Functional API
multiple inputs->multiple outputs

In [84]:
import numpy as np
import tensorflow as tf

x_train = np.array([[1], [2], [3], [4], [5]], dtype=np.float32)
y_train = np.array([[3], [5], [7], [9], [11]], dtype=np.float32)
inputs = tf.keras.Input(shape=(1,))
outputs = tf.keras.layers.Dense(1)(inputs)

#Functional
model = tf.keras.Model(inputs=inputs, outputs=outputs)

model.compile(
    optimizer=tf.keras.optimizers.SGD(learning_rate=0.01),
    loss="mse"
)

model.fit(x_train, y_train, epochs=500, verbose=0)

print(model.predict(np.array([[6]], dtype=np.float32)))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
[[13.03302]]


# Softmax

In [85]:
import tensorflow as tf

# Raw output from the model (Logits)
# Dog: 2.0, Cat: 1.0, Bird: 0.1
logits = tf.constant([2.0, 1.0, 0.1])

probabilities = tf.nn.softmax(logits)

print(probabilities.numpy())

[0.6590011  0.24243298 0.09856588]


In [87]:
prediction = tf.argmax(probabilities)

print(prediction.numpy())
#If the output is 0, the final prediction is Dog.
#If the output is 1, it’s Cat.
#If the output is 2, it’s Bird.

0
